sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t yazovaliyski/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run yazovaliyski/react-test npm test -- --coverage

after_success:
  - docker build -t yazovaliyski/multi-client ./client
  - docker build -t yazovaliyski/nginx ./nginx
  - docker build -t yazovaliyski/multi-server ./server
  - docker build -t yazovaliyski/multi-worker ./worker
  # Docker login

  - echo "$docker_password" | docker login -u "$docker_id" --password-stdin
  # Take those images and push to Docker HUB
  - docker push yazovaliyski/multi-client
  - docker push yazovaliyski/multi-server
  - docker push yazovaliyski/multi-worker
  - docker push yazovaliyski/nginx